### ISSUE TITLE
Auth config no longer honored when calling Docker.prototype.pull

### ISSUE THREAD

**Issue by gregarndt** [apocas/dockerode#139]
In a recent commit [1] `Docker.prototype.pull` was refactored and dropped the ability to pass in authconfig to `Docker.prototype.createImage`.  This prevents private images from being retrieved from a registry.

If the pull method should remain simpler and smaller, and the createImage api not be broken, then perhaps this [2] could be changed to:

`auth = opts.authconfig || undefined;`

Although it would be clearer if .pull passed in the right arguments.

I was not sure which way you would want this changed, but I could submit a PR for an agreed upon way.

[1] https://github.com/apocas/dockerode/commit/df15297f33ce2df9c15393173427523ebf4f3e4e
[2] https://github.com/apocas/dockerode/blob/master/lib/docker.js#L49

**Comment by apocas** [comment]
Ah crap, I knew I was missing something! That sneaky auth parameter in createImage.

Pull was a bit messy before and the separated auth parameter in createImage is a bit wacky too since authentication is something to be passed to Docker.

So let's do the "auth = opts.authconfig || undefined;" fix in createImage, this way in the next major bump we will probably change the createImage signature.
Think is probably the best route.

PS: Tests need to be improved for this use case.

**Comment by apocas** [comment]
Since this is kind of a major bug, I will commit and publish right away in order to minimize the impact of this.

Really sorry for not waiting for your PR.

**Comment by apocas** [comment]
Published in v2.1.4

**Comment by gregarndt** [comment]
Ah thank you! Sorry for not being able to respond sooner.
