### ISSUE TITLE
confused about lifecycle

### ISSUE THREAD

**Issue by jmls** [apocas/dockerode#150]
I'm trying to run a command on a container that may take some time to complete. Once it has completed, I want the container to be removed.

```javascript
    docker.createContainer(
                    {
                        Image: 'ubuntu', 
                        Cmd: ["myCommand"],
                    }, 

                    function (err, container) {
                        container.start(function(err,result) {
                            // started - but how to tell when finished ?
                        })
                    }
                )       
```

so, I create the container, and start the container .. however how can I tell when the container has finished the command so that I can stop/remove it (I am assuming that when the command has finished the container is automatically stopped)

**Comment by apocas** [comment]
In order to know when does the container finished you should use the container.wait method.

Check this: https://github.com/apocas/dockerode/blob/master/examples/run_stdin.js#L57
or this
https://github.com/apocas/dockerode/blob/master/test/container.js#L104

Then in the container.wait callback you can just call container.remove
