### ISSUE TITLE
tests broken?

### ISSUE THREAD

**Issue by electricmonk** [apocas/dockerode#190]
Hi,
I just cloned the project. Running on OS X 10.10.5, Docker 1.9.0, docker-machine 0.5.0.

Running `npm test`, I get:
```
#docker #listVolumes should list volumes:
     Uncaught AssertionError: expected null to be an array
```

@apocas, Is that also for you? do you have a CI environment for this project? if not, CAN we have a CI environment? travis-ci runs Docker now.

**Comment by apocas** [comment]
Yes, that specific is due to the fact that volumes are yet to be published. (probably tonight)
And the fact that docker returns a null instead of an empty array when there's no volumes.

Yes I have my private CI.

FYI:
Some versions of node may break tests (EPIPE error) due to this "bug": https://github.com/nodejs/node/issues/3803#issuecomment-158253328
