### ISSUE TITLE
Extending Documentation

### ISSUE THREAD

**Issue by cemersoz** [apocas/dockerode#243]
I am extending the Dockerode API as part of a project I am working on, and would like to begin documenting the Dockerode API.  Any suggestions as to how to proceed before I begin?

**Comment by DinisCruz** [comment]
Project pages in markdown are a great way to do it (specially since you can then receive PRs for it)

I usually use an issue to write the first pass of the content and to capture screenshots

for a good example see https://github.com/electron/electron/blob/master/docs/api/browser-window.md which is linked from https://github.com/electron/electron/tree/master/docs

**Comment by apocas** [comment]
Old issue, if needed it will be reopened.
