### ISSUE TITLE
Any tips regarding how to configure this to work with ECS?

### ISSUE THREAD

**Issue by jayantbh** [apocas/dockerode#283]

**Comment by apocas** [comment]
Could you provide more details?

**Comment by jayantbh** [comment]
Using dockerode, I can create and communicate with containers. Can I do that with containers inside ECS?

**Comment by Seikho** [comment]
You should be able to push to and pull from an ECS registry.
It's unclear from their documentation if you would be able to create containers. If you have SSH access to the server that creates the Docker containers, you can create the containers using SSH tunneling and dockerode.

**Comment by jayantbh** [comment]
Their API provides no way to create containers like `docker run ...`. Instead, I can run tasks, which are containers, sure, but not what I need. I need very direct control over each container.

Do you think ECS is not what I need then?
And, if so, what do you suggest about Kubernetes?

The end goal remains the same, I want to use dockerode with one of them, and I want complete control over each container, and not run them like tasks.

**Comment by JosselinTD** [comment]
I'm trying to use ECS with dockerode to.
I can start tasks (container) that will never finish (using entrypoint 'sleep inf') and now, I try to connect dockerode to the containers (not working at the moment of this message).
I plan to execute a bunch of command inside the container before killing it.

During my try, I discover that the "tasks" will automatically finish (and so, close the containers) when the entrypoint (or CMD, it's still not very clear to me) end. 'sleep inf' prevent this and give me a container on which I can work.

I still don't know if it's simplier to just work directly with EC2 instances instead of ECS which is just a wrapper of EC2 and other stuffs, I try everything and see it later ^^

Do you know how to connect dockerode to the docker in a EC2 ? Or directly to a container ?

**Comment by jayantbh** [comment]
@JosselinTD yeah, I'm running a docker swarm on a bunch on EC2 instances.

This [docker documentation](https://docs.docker.com/swarm/install-manual/) on swarm clusters helped me immesely.
This is the [local swarm setup](https://docs.docker.com/swarm/install-w-machine/) documentation.

If you're not looking for swarm, then you can just set up remote API on a server and use it.
