### ISSUE TITLE
Container.inspect uses malformed path because "this.id" is not a string

### ISSUE THREAD

**Issue by matutter** [apocas/dockerode#303]
When a container has been stopped and a `Docker.getContainer("name")` is called on it, the containers id field is set incorrectly. It sets the Container.id field to the object `{ "id":"b45...39" }` which when `Container.inspect({}, (e, data) => { console.log(e) })` is called throws an error because the URI used to make the request is something like, `{"path":"/containers/[Object object]/json?"}`.

``` shell
docker run -d -p 5000:5000 --restart=always --name registry registry:2
docker stop registry
```

``` javascript
const Docker = require('dockerode')
var local = new Docker()
var registry = local.getContainer("registry")
// registry.id = registry.id.id || registry.id // fixes it
registry.start({}, (e, data) => {
  // e == TypeError: Requested path contains escaped characters
})
```

**Comment by apocas** [comment]
Can't replicate this.

It's weird the fact you were getting "[Object object]" in the URI, event with the container stopped.
I think there may have been other underlying reason for it to happen.

Going to close this one for now since I can't replicate it, but feel free to reopen/update it if needed :)
