### ISSUE TITLE
Empty callback on start stop delete

### ISSUE THREAD

**Issue by arckosfr** [apocas/dockerode#316]
Hello,
Actually when i invoke a stop/start/delete on a container, if its good (200) i have a "" callback

```javascript
docker.delete = function(id, cb) {
    var container = docker.getContainer(id);
    container.remove(function(err, data) {
        if (err) {
            cb(err);
        } else {
            cb(data);
        }
    });
};
```

Is it a bad use or a bug ?
Thanks

**Comment by LaurensRietveld** [comment]
I had the same experience. Guess this is because dockerode follows the API quite strictly, and the API is returning a `no-content` response in these situations. 
For this library, it would be nice to return the container class though, for easier chaining with things like promises

**Comment by arckosfr** [comment]
ATM i have added a response, its a sad tweak but better than nothing : 
example : 
```
docker.start = function(id,cb) {
	var container = docker.getContainer(id);
	container.start(function(err,data) {
    if (err) {
      cb(err);
    } else {
      cb({id : container.id, statusCode : 200});
    }
	});
};
```

**Comment by apocas** [comment]
Yes @LaurensRietveld is right.

https://github.com/apocas/dockerode/blob/master/test/container.js#L111 data is empty in these situations.

It could return something redundant (you already have all the info, since there is no new state).
But then we were going to get in trouble if the API spec changes, it's hard to make everyone happy. So we follow API behaviour.

**Comment by arckosfr** [comment]
Oh ok,
I don't ask for change only if the return is normally empty.
So yes (i understand that is no need to change this)
thanks you all (dockerode is freaking good 👍 )
