### ISSUE TITLE
docker.run and stdin

### ISSUE THREAD

**Issue by lezsakdomi** [apocas/dockerode#455]
Seems like the `stream` parameter of `docker.run` can not be considered as input stream using `Tty: true`.

I've used this code:
```javascript
const stream = webscoketStream(socket, {binary: true});
docker.run('ubuntu', null, stream, {
    Tty: true,
});
```
...where `socket` is a valid `ws` socket.
I can see the output, but I can't type.

Please not that in expense this code works:
```javascript
docker.createContainer({
    'Tty': true,
    'OpenStdin': true,
    'Image': 'ubuntu',
}, ttry((err, container) => {
    if (err) throw err;

    container.attach({
        stream: true,
        stdin: true,
        stdout: true,
        stderr: true,
    }, ttry((err, dockerStream) => {
        if (err) throw err;

        const remoteStream = webscoketStream(socket, {
            binary: true
        });

        dockerStream.pipe(remoteStream);
        remoteStream.pipe(dockerStream);

        container.start(ttry((err, data) => {
            if (err) throw err;

            container.resize(info.req.params);

            container.wait(ttry((err, data) => {
                if (err) throw err;

                socket.send(JSON.stringify(data));
                socket.close();
            }))
        }));
    }));
}));
```

**Comment by marcj** [comment]
For all people coming across this: Most commands require to receive a EOF for its stdin. Dockerode does not close the stdin automatically, nor does it by calling `stream.end('myfinaldata')`. So your only chance to get around that is to not directly pipe the input into your command of choice.

An example for node:

```javascript
localDocker.createContainer({
  Image: 'node:10-alpine',
  HostConfig: {
    AutoRemove: true
  },
  OpenStdin: true,
  Cmd: ['sh']
}, function (err, container) {
  container.attach({ stream: true, hijack: true, stdin: true, stdout: true, stderr: true }, function (err, stream) {
    if (err) throw err;

    dockerStream.pipe(process.stdout);

    const code = `console.log(123)`;
    stream.write(`echo "eval(${JSON.stringify(JSON.stringify(code)).slice(1, -1)})" | node;exit;\n`);

    container.start(function (err, data) {
      if (err) throw err;
    })
  })
})
```

**Comment by marcj** [comment]
Ok, here's an update. When you not use `Tty: true` like the author of this issue did, you get as output a multiplexed stream, where stdout and stderr is separated and need to be binary parsed.

See [Docker API documentation](https://docs.docker.com/engine/api/v1.24/):

> When using the TTY setting is enabled in POST /containers/create , the stream is the raw data 
> from the process PTY and client’s stdin. When the TTY is disabled, then the stream is multiplexed > to separate stdout and stderr.

The actual issue is now, that when you want to pass data into `docker.run`'s stdin that is not from a terminal, like piping a file or binary data, you need to disable `Tty`. But, when you disable `Tty` Docker does not close automatically the stdin stream of the target command. Also you get as output the multiplexed format, which you need to parse first, and you need to set `hijack: true` for `container.attach` to upgrade the connection first. To close the stdin automatically, you need to use `StdinOnce`. This changes the behavior entirely compared to the Tty version. So to make stuff simple, I create a Typescript function that should do the trick. It's unfortunately a bit more work, but we could integrate that into Dockerode if there's demand.

https://gist.github.com/marcj/f026939066dc32568b05ed4a179c2222

```typescript
    const file = fs.createReadStream(__dirname + '/test.ts');
    const a = await dockerRunWithStdIn(docker, file, {
        containerName: 'peter',
        image: 'node:12-alpine',
        cmd: ['wc', '-l'],
        hostConfig: {AutoRemove: true}
    });
    console.log('Answer:', a.toString());
```

**Comment by Dagdelo** [comment]
@marcj thx for the solution! The PR will be valuable until this happens I will use your code.
