### ISSUE TITLE
Build Image from Git

### ISSUE THREAD

**Issue by makkmarci13** [apocas/dockerode#471]
My code:
> docker.buildImage({'remote': 'https://github.com/makkmarci13/docker-mtasa.git'}, {t: 'mtasa-1003', 'build-arg': { 'MTA_USER': '1003' }}, function (err, response){
    if (err) console.log(err);
    else console.log('success');
});

Run error:
![image](https://user-images.githubusercontent.com/15845442/43545477-45e945c6-95d6-11e8-8ac6-907a0bc7dabf.png)
Is there any way to achieve what I am trying to do?

**Comment by DenSpirit** [comment]
You need to supply the 'remote' key in options to the request and supply something (like an empty string) as the first argument.

I could not make your case work regardless because Docker would not accept the url, or the url to your Dockerfile in github. Maybe passing a git url (not HTTPS) could work here.
