### ISSUE TITLE
docker-compose

### ISSUE THREAD

**Issue by peterpetre** [apocas/dockerode#547]
Can I run docker-compose somehow? e.g. docker.compose(...)

**Comment by luckstar77** [comment]
I'm also curious about this.

**Comment by pachkovska** [comment]
any updates on this ?

**Comment by Fi1osof** [comment]
+1

**Comment by apocas** [comment]
docker-compose (https://github.com/docker/compose) is a CLI app that implements a driver like dockerode (https://github.com/docker/compose/blob/84afa518e8144c9620562c023c0b62dd7c0b4305/compose/cli/docker_client.py#L118), interprets a YAML file (docker-compose.yml) and instantiates all the needed state (containers, etc) in docker.

They are basically different tools for different problems :)

Although someone could implement a "programatically friendly docker-compose" by building a parser for docker-compose.yml (https://docs.docker.com/compose/compose-file/) with a API interface and use dockerode for the docker operations.

Not sure if makes sense to push this effort into dockerode, since the idea of it is exactly allowing everyone to create tools like this one in it's "userland" :)

**Comment by apocas** [comment]
https://github.com/apocas/dockerode-compose
I'm going to start working on this :)

**Comment by apocas** [comment]
Follow this issue on the repo (working and published):
https://github.com/apocas/dockerode-compose
