### ISSUE TITLE
docker.run problem

### ISSUE THREAD

**Issue by MrVapor01** [apocas/dockerode#599]
moin, I have a little problem. If I create a container with docker.run it starts but I don't get a result only if I stop or delete the container manually then I get the result. What am I doing wrong?
`
    const docker = new Docker({host: "127.0.0.1", port: 2375});
    docker.run('mariadb',
        [], [] ,{
            name: 'mariadb-01',
            Hostconfig: {PortBindings: {'3306/tcp': [{HostIP: "0.0.0.0", HostPort: '3309'}]}},
            Env: ["MYSQL_ROOT_PASSWORD=1234"]
        }, {},  function (err, data, container) {
            if (err) {
                console.error(err);
                return;
            }
            console.log(data)
            console.log(container)
            res.status(200).json({success: true, message: 'Das image ' + image + ' wurde erfolgreich getstartet!'})
        });

`

**Comment by gateian** [comment]
I'm looking at this issue at the moment, however perhaps it is by design. The documentation say: 

`callback - callback called when execution ends (optional, promise will be returned if not used).`

Meaning that it doesn't callback when there was a successful run command, but after the container has finished "running".  If that's the case, then it would be good to get a callback for when the container is successfully up and running.
