### ISSUE TITLE
Question: Using options on run method

### ISSUE THREAD

**Issue by joeyhipolito** [apocas/dockerode#93]
I am pretty much lost in using the docker.run command, the documentationd doesn't say much either.

For example how do I use `--volumes-from`?

in cli

```
docker run --rm --volumes-from data -t git-clone https://some.git
```

my attempt 

```
docker.run('git-clone', ['--rm', '--volumes-from data', url], function(err, data){
   console.log(data);
});
```

**Comment by reekoheek** [comment]
I found that from the API documentation (v1.17) (https://docs.docker.com/reference/api/docker_remote_api_v1.17/), there is VolumesFrom key at HostConfig. But I havent success yet to bind other container volumes into container.

This case I'm using:

```
$ docker version
Client version: 1.5.0
Client API version: 1.17
Go version (client): go1.4.1
Git commit (client): a8a31ef
OS/Arch (client): darwin/amd64
Server version: 1.5.0
Server API version: 1.17
Go version (server): go1.4.1
Git commit (server): a8a31ef
```

I use `docker create` to register container to start later, instead of `docker run` to run immediately, but I think the options is identically can be applied to `docker run`. 

```
docker.createContainer(opts, function() {});
```

Here is the options(opts) I told about.
```
{
  "HostConfig": {
    "VolumesFrom": [ "another-container-name" ]
  }
}
```

Are there anything I've had missed there?
